// <auto-generated />
using System;
using InfrastructureDB.Data.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InfrastructureDB.Migrations
{
    [DbContext(typeof(PostgresDataContext))]
    [Migration("20250731145056_migration_20250731")]
    partial class migration_20250731
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("kurier")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kurier.Common.Models.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("DepartureAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders", "kurier");

                    b.HasData(
                        new
                        {
                            Id = new Guid("56a302e2-675a-45ab-ae0e-535e2f36ee0f"),
                            Created = new DateTime(2025, 2, 7, 20, 35, 10, 489, DateTimeKind.Local).AddTicks(6107),
                            DeliveryAddress = "пр. 1905 года, д. 92, кв. 83",
                            DepartureAddress = "шоссе Ленина, д. 93, кв. 10",
                            LastUpdate = new DateTime(2025, 2, 7, 20, 35, 10, 490, DateTimeKind.Local).AddTicks(8626),
                            Status = 0,
                            UserId = new Guid("224d30a8-c2a1-4c5e-b84d-0e018ce67a7d"),
                            Weight = 4.0m
                        },
                        new
                        {
                            Id = new Guid("f8e666d8-0f7f-4c56-b575-d5fc30bfeb39"),
                            Created = new DateTime(2025, 2, 7, 20, 35, 10, 490, DateTimeKind.Local).AddTicks(9974),
                            DeliveryAddress = "наб. Бухарестская, д. 11, кв. 35",
                            DepartureAddress = "пл. Сталина, д. 62, кв. 49",
                            LastUpdate = new DateTime(2025, 2, 7, 20, 35, 10, 490, DateTimeKind.Local).AddTicks(9977),
                            Status = 0,
                            UserId = new Guid("bf36603a-5b14-4b1b-bae4-e9a59c8d9dbd"),
                            Weight = 10.0m
                        });
                });

            modelBuilder.Entity("Kurier.Common.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Permissions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("Users", "kurier");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5b09eec7-452b-4b0d-875f-472d8f3babd1"),
                            Email = "ekat.grig@kurier.ru",
                            Name = "Екатерина Григорьева",
                            Password = "5tgbwdsaf093",
                            Permissions = 4064
                        },
                        new
                        {
                            Id = new Guid("0af2685a-16d7-4842-9d40-397e9166dd53"),
                            Email = "adam.nick@kurier.ru",
                            Name = "Адам Николаев",
                            Password = "ds;ljkfhatfgil34",
                            Permissions = 24
                        },
                        new
                        {
                            Id = new Guid("9a78b69e-8049-4daf-9a99-8398b58791ef"),
                            Email = "matveytokarev@kurier.ru",
                            Name = "Матвей Токарев",
                            Password = "pikjsr7e8ftg2w4r",
                            Permissions = 24
                        },
                        new
                        {
                            Id = new Guid("28c02b6f-a4fd-41f2-b0e9-a0bfa0bbf7af"),
                            Email = "ilya_bog@mail.ru",
                            Name = "Илья Богданов",
                            Password = ",lsdafjk0982",
                            Permissions = 7
                        },
                        new
                        {
                            Id = new Guid("224d30a8-c2a1-4c5e-b84d-0e018ce67a7d"),
                            Email = "nikolaeva.d.d@yandex.ru",
                            Name = "Дарина Николаева",
                            Password = "kmvw8234r",
                            Permissions = 7
                        },
                        new
                        {
                            Id = new Guid("bf36603a-5b14-4b1b-bae4-e9a59c8d9dbd"),
                            Email = "maxxmirno@google.com",
                            Name = "Максим Смирнов",
                            Password = "mbge089yw=",
                            Permissions = 7
                        });
                });

            modelBuilder.Entity("Kurier.Common.Models.Entities.Order", b =>
                {
                    b.HasOne("Kurier.Common.Models.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kurier.Common.Models.Entities.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
